# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm-c' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for mvvm-c
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'R.swift'
  pod 'Alamofire'

  target 'mvvm-cTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mvvm-cUITests' do
    # Pods for testing
  end

end
