# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm-c' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mvvm-c
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'R.swift'
  pod 'RxSwiftExt'
  pod 'RxGesture'
  pod 'Alamofire'
  pod 'SnapKit'

  target 'mvvm-cTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
  end

  target 'mvvm-cUITests' do
    # Pods for testing
  end

end
